[window]
padding.x = 2
padding.y = 2
decorations = "Full"

[font]
size = 17.0
normal.family = "VictorMono Nerd Font"
normal.style = "Medium"
bold.family = "VictorMono Nerd Font"
bold.style = "Bold"
italic.family = "VictorMono Nerd Font"
italic.style = "Medium Italic"
bold_italic.family = "VictorMono Nerd Font"
bold_italic.style = "Bold Italic"

[colors]
# Default colors
[colors.primary]
background = "0x1b182c"
foreground = "0xcbe3e7"

# Normal colors
[colors.normal]
black = "0x100e23"
red = "0xff8080"
green = "0x95ffa4"
yellow = "0xffe9aa"
blue = "0x91ddff"
magenta = "0xc991e1"
cyan = "0xaaffe4"
white = "0xcbe3e7"

# Bright colors
[colors.bright]
black = "0x565575"
red = "0xff5458"
green = "0x62d196"
yellow = "0xffb378"
blue = "0x65b2ff"
magenta = "0x906cff"
cyan = "0x63f2f1"
white = "0xa6b3cc"
